import Head from "next/head";
import { Container, Form, Button } from "react-bootstrap";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}` + 'd-flex w-100'}>
        <Container className="p-4 d-flex justify-content-center align-items-center" >
          <Form className="p-5 fs-4 border border-secondary" >
            <Form.Group className="mb-3" controlId="exampleForm.ControlInput1">
              <Form.Label>Username</Form.Label>
              <Form.Control type="email" placeholder="name@example.com" />
            </Form.Group>
            <Form.Group className="mb-3" controlId="exampleForm.ControlTextarea1">
              <Form.Label>Password</Form.Label>
              <Form.Control type="password"/>
            </Form.Group>
            <Button type='submit'>Submit</Button>
          </Form>
        </Container>
      </main>
    </>
  );
}
