import Head from "next/head";
import { Container, Form, Button } from "react-bootstrap";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter()
  const [admin, setAdmin] = useState({
    username: '',
    password: '',
  })
  const [error, setError] = useState(null)

  function handleChange(e) {
    setAdmin({ ...admin, [e.target.name]: e.target.value })
  }

  function submit() {
    fetch(`${process.env.NEXT_PUBLIC_API_URL}/admin/login`, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(admin),
    }).then(res => res.json()).then(data => {
      if (data.success === true) {
        localStorage.setItem('admin-token', data.token);
        router.push('/products');
      } else {
        setError(data)
      }
    }).catch(error => console.log(error))
  }



  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}` + 'd-flex w-100'}>
        <Container className="p-4 d-flex justify-content-center align-items-center" >
          <Form className="p-5 fs-4 border border-secondary" >
            {error && <p style={{ color: 'red' }}>{error.message + ', Try again'}</p>}
            <Form.Group className="mb-3" controlId="exampleForm.ControlInput1">
              <Form.Label>Username</Form.Label>
              <Form.Control type="text" onChange={(e) => handleChange(e)} name='username' placeholder="username" />
            </Form.Group>
            <Form.Group className="mb-3" controlId="exampleForm.ControlTextarea1">
              <Form.Label>Password</Form.Label>
              <Form.Control onChange={(e) => handleChange(e)} name='password' type="password" />
            </Form.Group>
            <Button onClick={submit}>Submit</Button>
          </Form>
        </Container>
      </main>
    </>
  );
}
